# Generated by Django 3.1.4 on 2021-02-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210125_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Guesthouse', 'Guesthouse'), ('Hotel', 'Hotel'), ('Townhouse', 'Townhouse'), ('Plots', 'Plots'), ('Shops', 'Shops'), ('Office', 'Office')], default='Home', max_length=50),
        ),
    ]
