# Generated by Django 3.1.4 on 2021-03-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20210303_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='property_availability',
        ),
        migrations.AddField(
            model_name='listing',
            name='open_house',
            field=models.BooleanField(default=False),
        ),
    ]
