# Generated by Django 3.1.4 on 2021-07-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20210516_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Guesthouse', 'Guesthouse'), ('Ladies-hostels', 'Ladies Hostels'), ('Gents-hostels', 'Gents Hostels'), ('Bedsitter', 'Bedsitter'), ('Townhouse', 'Townhouse'), ('Plots', 'Plots'), ('Warehouse', 'Warehouse'), ('Land', 'Land'), ('Shops', 'Shops'), ('Office', 'Office')], default='Home', max_length=50),
        ),
    ]
