# Generated by Django 3.1.4 on 2021-07-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_auto_20210721_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Guesthouse', 'Guesthouse'), ('Ladies Hostels', 'Ladieshostels'), ('Gents Hostels', 'Gentshostels'), ('Bedsitter', 'Bedsitter'), ('Townhouse', 'Townhouse'), ('Plots', 'Plots'), ('Warehouse', 'Warehouse'), ('Land', 'Land'), ('Shops', 'Shops'), ('Office', 'Office')], default='Home', max_length=50),
        ),
    ]
