# Generated by Django 3.1.4 on 2021-01-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20201227_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='home_type',
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Guest House', 'Guest'), ('hotel', 'Hotel'), ('Townhouse', 'Townhouse'), ('plots', 'Plots'), ('shops', 'Shops'), ('Office', 'Office')], default='Home', max_length=50),
        ),
    ]
