# Generated by Django 3.1.4 on 2021-01-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20210112_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='open_house',
        ),
        migrations.AddField(
            model_name='listing',
            name='property_availability',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Guesthouse', 'Guesthouse'), ('hotel', 'Hotel'), ('Townhouse', 'Townhouse'), ('plots', 'Plots'), ('shops', 'Shops'), ('Office', 'Office')], default='Home', max_length=50),
        ),
    ]
