# Generated by Django 3.1.4 on 2021-01-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20210125_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_availability',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=50),
        ),
    ]
