# Generated by Django 3.1.4 on 2021-04-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20210413_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rate',
            field=models.CharField(choices=[('Per Night', 'Per Night'), ('Per Month', 'Per Month')], default='Per Month', max_length=50),
        ),
    ]
